### ISSUE TITLE
Upgrading Issue

### ISSUE THREAD

**Issue by Joe-Giambrone** [workarea-commerce/workarea-global-e#7]
Not sure if bug or not or where else to put this. We are currently upgrading Workarea from 3.3.35 to 3.4 newest. My issue is that this gem's gemspec goes from less than 3.4 in v1.2.1 to ~> 3.4.25 in v1.3. There is nothing in between. This is making upgrading a bit more difficult as I can not do any smaller upgrades to get us up to newest.  Any suggestions on making life a little bit easier?

**Comment by bencrouse** [comment]
I'm not sure why that was set, but I have to assume it depended on some fixes in base. If you want to test out changing the dependency and report back, we can change the dependency the gemspec. Otherwise, I'm closing since this isn't really an issue with the plugin.
